services:
  claude-mcp:
    image: claude-mcp
    environment:
      - GIT_USER_NAME=${GIT_USER_NAME}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - ANTHROPIC_MODEL=${ANTHROPIC_MODEL}
      - CLAUDE_CODE_MAX_OUTPUT_TOKENS=${CLAUDE_CODE_MAX_OUTPUT_TOKENS}
      - MAX_THINKING_TOKENS=${MAX_THINKING_TOKENS}
    volumes:
      - ${WORKSPACE_DIR:-.}:/workspace
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Docker-in-Docker for MCP
    working_dir: /workspace
    stdin_open: true
    tty: true
    privileged: true  # Required for Docker-in-Docker

# To run podman compose run claude-mcp