services:
  claude-mcp:
    image: claude-mcp
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
    volumes:
      - ${WORKSPACE_DIR:-.}:/workspace
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Docker-in-Docker for MCP
    working_dir: /workspace
    stdin_open: true
    tty: true
    privileged: true  # Required for Docker-in-Docker

# Works with your current start-claude.ps1